### ISSUE TITLE
Fix the link div on the main page

### ISSUE THREAD

**Issue by beingnoble03** [noble-mittal/noble-mittal.github.io#3]
Currently the width of the 3 link buttons is fixed instead we should use `flex-box` to make it compatible for all devices. The width of the button should remain as it is.

<img width="1440" alt="Screenshot 2022-10-02 at 4 47 53 PM" src="https://user-images.githubusercontent.com/62551163/193451221-63aee9d6-47ea-43a6-a302-cd6456514a64.png">

**Comment by pratiksrivastava01** [comment]
@beingnoble03 do you mean that all the links should be aligned vertical column-wise when we see them on mobile and other small devices

**Comment by beingnoble03** [comment]
Yes, @pratiksrivastava01. For example, in the issue image, the instagram button should be shifted to next row.

**Comment by pratiksrivastava01** [comment]
ok can you assign me this @beingnoble03

**Comment by shivansh12032004** [comment]
@beingnoble03  assign me this issue, I'll work on this

**Comment by beingnoble03** [comment]
> ok can you assign me this @beingnoble03

@pratiksrivastava01 Sounds good. You can work on this issue.

**Comment by beingnoble03** [comment]
Sorry @shivansh12032004. I assignedd this issue to @pratiksrivastava01. You can work on #4 after resolving this issue. Thanks!

**Comment by DevTomilola-OS** [comment]
Can i work on this? Assign me.

**Comment by beingnoble03** [comment]
> Can i work on this? Assign me.

Sorry @DevTomilola-OS. This issue is already assigned to someone.

**Comment by DevTomilola-OS** [comment]
Oh okay, thanks for the response. I'm open to work on any other issue if available.

**Comment by beingnoble03** [comment]
@DevTomilola-OS All the issues are assigned. You may create your own valid issue and get it assigned.

**Comment by DevTomilola-OS** [comment]
okay thanks.

**Comment by pratiksrivastava01** [comment]
@beingnoble03  is this looks good
![image](https://user-images.githubusercontent.com/92784294/193560013-64fafa46-e767-40d5-9593-5c350a425dd2.png)

**Comment by beingnoble03** [comment]
@pratiksrivastava01 Open a pull request for the changes you have made. Will review it in PR itself.

**Comment by pratiksrivastava01** [comment]
Ok
