### ISSUE TITLE
Hover over social links on light mode

### ISSUE THREAD

**Issue by shivansh12032004** [noble-mittal/noble-mittal.github.io#5]
![2022-10-02](https://user-images.githubusercontent.com/99906801/193451734-4b4d005a-cf49-4853-95e5-ebb07a5fc299.png)
The colours on hover just don't match. assign me this issue to make ui/ux more attractive

**Comment by beingnoble03** [comment]
@shivansh12032004 great idea. Thanks!

**Comment by beingnoble03** [comment]
@shivansh12032004 are you still working on it? If not, I can assign this issue to someone else.
